using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using static BlogApp.Infrastructure.Common.ValidationConstants;

namespace BlogApp.Infrastructure.Data.Models
{
    /// <summary>
    /// Represents a content category for organizing and filtering blog posts.
    /// 
    /// Categories provide a hierarchical way to organize blog content. Each post can belong
    /// to multiple categories through the PostCategory junction table, enabling flexible
    /// content classification and discovery.
    /// </summary>
    public class Category
    {
        /// <summary>
        /// Primary key identifier for the category.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [Comment("Category identifier")]
        public int Id { get; set; }

        /// <summary>
        /// The category name displayed to users when browsing or filtering posts.
        /// Length: 3-50 characters (defined in ValidationConstants)
        /// Must be unique within the system.
        /// Examples: "Technology", "Travel", "Food", "Lifestyle"
        /// </summary>
        [Required]
        [Comment("Category name")]
        [StringLength(CategoryNameMax, MinimumLength = CategoryNameMin)]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Collection of PostCategory junction records linking this category to posts.
        /// Enables many-to-many relationship between posts and categories.
        /// A post can belong to multiple categories, and a category can contain multiple posts.
        /// </summary>
        public ICollection<PostCategory> PostsCategories { get; set; } = new HashSet<PostCategory>();
    }
}
