using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static BlogApp.Infrastructure.Common.ValidationConstants;

namespace BlogApp.Infrastructure.Data.Models
{
    /// <summary>
    /// Represents a comment made on a blog post.
    /// 
    /// Comments allow readers to engage with blog content and authors.
    /// Each comment is associated with a specific post and user, and can receive likes from other users.
    /// Comments can be moderated by administrators for policy violations.
    /// </summary>
    public class Comment
    {
        /// <summary>
        /// Primary key identifier for the comment.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [Comment("Comment identifier")]
        public int Id { get; set; }

        /// <summary>
        /// The text content of the comment.
        /// Length: 5-5000 characters (defined in ValidationConstants)
        /// Can contain plain text or basic HTML formatting (after sanitization).
        /// </summary>
        [Required]
        [Comment("Comment content")]
        [StringLength(CommentContentMax, MinimumLength = CommentContentMin)]
        public string Content { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key to the ApplicationUser who authored this comment.
        /// Establishes the creator relationship for tracking comment ownership and moderation.
        /// </summary>
        [Required]
        [Comment("Application user and commen creator identifier")]
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Navigation property to the ApplicationUser who created this comment.
        /// Allows access to user information including name, warnings, and ban status.
        /// </summary>
        [ForeignKey(nameof(UserId))]
        public ApplicationUser User { get; set; } = null!;

        /// <summary>
        /// Foreign key to the Post this comment belongs to.
        /// Establishes the relationship between comment and its parent post.
        /// </summary>
        [Required]
        [Comment("Post identifier")]
        public int PostId { get; set; }

        /// <summary>
        /// Navigation property to the Post this comment is attached to.
        /// Comments are always associated with exactly one post.
        /// </summary>
        [ForeignKey(nameof(PostId))]
        public Post Post { get; set; } = null!;

        /// <summary>
        /// Timestamp when the comment was created.
        /// Set automatically when comment is first created.
        /// Used for sorting comments chronologically.
        /// </summary>
        [Required]
        public DateTime CommentUploadDate { get; set; }

        /// <summary>
        /// Collection of likes this comment has received from other users.
        /// Tracks user engagement with the comment.
        /// Likes/dislikes help surface helpful comments.
        /// </summary>
        public ICollection<CommentLike> CommentsLikes { get; set; } = new List<CommentLike>();
    }
}
