using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using static BlogApp.Infrastructure.Common.ValidationConstants;

namespace BlogApp.Infrastructure.Data.Models
{
    /// <summary>
    /// Represents a tag for organizing and filtering blog posts.
    /// 
    /// Tags provide fine-grained content classification. Posts can have multiple tags,
    /// and tags can be applied to many posts through the PostTag junction table.
    /// Tags enable keyword-based searching and content discovery.
    /// </summary>
    public class Tag
    {
        /// <summary>
        /// Primary key identifier for the tag.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [Comment("Tag identifier")]
        public int Id { get; set; }

        /// <summary>
        /// The tag name or label.
        /// Length: 2-30 characters (defined in ValidationConstants)
        /// Examples: "ASP.NET", "Azure", "Performance", "Security"
        /// Must be unique within the system.
        /// </summary>
        [Required]
        [Comment("Tag name")]
        [StringLength(TagNameMax, MinimumLength = TagNameMin)]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Collection of PostTag junction records linking this tag to posts.
        /// Enables many-to-many relationship between posts and tags.
        /// A post can have multiple tags, and a tag can be applied to multiple posts.
        /// </summary>
        public ICollection<PostTag> PostsTags { get; set; } = new HashSet<PostTag>();
    }
}
